// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExRKx5Iul5gYtkHjJQ8ts4mS9rxfTaUg',
    appId: '1:188850036653:web:a6339e7ee5f52273e2cb24',
    messagingSenderId: '188850036653',
    projectId: 'chatappflutter-40107',
    authDomain: 'chatappflutter-40107.firebaseapp.com',
    storageBucket: 'chatappflutter-40107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkq04bz8TPfC4Fz0eSQrWQ7RccTJ9PT4U',
    appId: '1:188850036653:android:0937bf0faa5eff42e2cb24',
    messagingSenderId: '188850036653',
    projectId: 'chatappflutter-40107',
    storageBucket: 'chatappflutter-40107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfmxXop0gYuYZtGRZqvX9p0gRbAZefL2k',
    appId: '1:188850036653:ios:84132931b6aee945e2cb24',
    messagingSenderId: '188850036653',
    projectId: 'chatappflutter-40107',
    storageBucket: 'chatappflutter-40107.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
